# Generated by Django 5.1.6 on 2025-05-14 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='vocas.meaning')),
                ('choice', models.ManyToManyField(to='vocas.meaning')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now=True)),
                ('question', models.ManyToManyField(related_name='questions', to='tests.question')),
            ],
        ),
    ]
