# Generated by Django 5.1.6 on 2025-05-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='day',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
