# Generated by Django 5.1.6 on 2025-03-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num',
        ),
    ]
