databases:
  - name: ebsvoca2026
    plan: free
    databaseName: ebsvoca2026
    user: ebsvoca2026
    region: singapore

services:
  - type: web
    plan: free
    name: ebsvoca2026
    runtime: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ebsvoca2026
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
