# Generated by Django 5.1.6 on 2025-03-02 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('adj', '형용사'), ('verb', '동사'), ('noun', '명사'), ('adv', '부사'), ('prep', '전치사')], max_length=10)),
                ('definition', models.TextField()),
                ('voca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='vocas.voca')),
            ],
        ),
    ]
